### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by ghost** [simmo/gulp-stats#7]
While using Gulp#4.0 got an error.

```

/node_modules/gulp-stats/index.js:39
        var totalTime    = process.hrtime(startTime),
                                   ^
TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at Gulp.<anonymous> (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp-stats/index.js:39:36)
    at Gulp.emit (events.js:129:20)
    at Object.after (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp/node_modules/undertaker/lib/helpers/createExtensions.js:46:10)
    at handler (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/lib/mapSeries.js:47:12)
    at f (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/now-and-later/node_modules/once/once.js:17:25)
    at f (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/node_modules/once/once.js:17:25)
    at done (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:26:12)
    at /Users/chaitanya/WebStormProjects/GulpAngular/node_modules/del/index.js:54:4
    at callback (/Users/chaitanya/WebStormProjects/GulpAngular/node_modules/del/node_modules/each-async/index.js:38:4)

```

**Comment by simmo** [comment]
Hi,

Gulp 4 isn't currently supported. I imagine this error is possibly due to the events being slightly different in Gulp 4.

Can you post your gulpfile?

Feel free to drop a pull request if you have a fix.

**Comment by Grawl** [comment]
@simmo I can post my `gulpfile.js` for testing Gulp 4.0 with the same error.

``` js
var gulp = require('gulp');
require('gulp-stats')(gulp);
function clean(cb) {
    console.log('clean');
    cb()
}
gulp.task('assemble', assemble);
function assemble(cb) {
    setTimeout(()=>{console.log('assemble')}, 5000);
    cb();
}
function watch(cb) {
    console.log('watch');
    cb();
}
gulp.task('default', gulp.series(clean, 'assemble', watch));
```

```
/Users/grawl/Sites/iastudio-markup/node_modules/gulp-stats/index.js:39
        var totalTime    = process.hrtime(startTime),
                                   ^

TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at Gulp.<anonymous> (/Users/grawl/Sites/iastudio-markup/node_modules/gulp-stats/index.js:39:36)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Object.after (/Users/grawl/Sites/iastudio-markup/node_modules/undertaker/lib/helpers/createExtensions.js:48:10)
    at handler (/Users/grawl/Sites/iastudio-markup/node_modules/now-and-later/lib/mapSeries.js:47:12)
    at f (/Users/grawl/Sites/iastudio-markup/node_modules/once/once.js:17:25)
    at f (/Users/grawl/Sites/iastudio-markup/node_modules/once/once.js:17:25)
    at done (/Users/grawl/Sites/iastudio-markup/node_modules/async-done/index.js:24:15)
    at clean (/Users/grawl/Sites/iastudio-markup/gulp4.js:5:2)
```

**Comment by generalov** [comment]
I've written an adapter to Gulp 4.0:

```JavaScript
function usingGulp4 (gulp) {
  let startTime = {};

  return {
    on (eventName, handle) {
      this[eventName](handle);
    },
    task_start (handle) {
      gulp.on('start', function (e) {
        startTime[e.uid] = e.time;
        handle();
      });
    },
    task_stop (handle) {
      gulp.on('stop', function (e) {
        handle({
          task: e.name,
          duration: (e.time - startTime[e.uid]) / 1000,
          hrDuration: e.duration
        });
      });
    },
    stop (handle) {
      gulp.on('stop', function (e) {
        delete startTime[e.uid];
        if (!Object.keys(startTime).length) {
          handle();
        }
      });
    }
  };
}

require('gulp-stats')(usingGulp4(gulp));
```

**Comment by mindpixel-labs** [comment]
@generalov This still seems to log native gulp series or parralell tasks. Should those not be excluded?

**Comment by mindpixel-labs** [comment]
@simmo It looks like Gulp 4.x has changed from Orchestrator to an entirely new task registry called Undertaker. Do you have any plans to upgrade this module properly for Gulp 4? It's such a lovely plugin.

**Comment by simmo** [comment]
To anyone that is interested I have Gulp 4 support in progress - https://github.com/simmo/gulp-stats/pull/10
